#include "Constants.h"

std::map<std::string, int> Constants::ARGUMENTS = {
    {IN_FILE_NAMEF, IN_FILE_CODE},  
    {IN_FILE_NAMES, IN_FILE_CODE},  
    {OUT_FILE_NAMEF, OUT_FILE_CODE},  
    {OUT_FILE_NAMES, OUT_FILE_CODE},  
    {ENCRYPT_MODE_NAMEF, ENCRYPT_MODE_CODE},  
    {ENCRYPT_MODE_NAMES, ENCRYPT_MODE_CODE},  
    {DECRYPT_MODE_NAMEF, DECRYPT_MODE_CODE},  
    {DECRYPT_MODE_NAMES, DECRYPT_MODE_CODE},  
    {GENERATE_KEY_MODE_NAMEF, GENERATE_KEY_MODE_CODE},  
    {GENERATE_KEY_MODE_NAMES, GENERATE_KEY_MODE_CODE},  
    {PUBLIC_KEY_NAMEF, PUBLIC_KEY_CODE},  
    {PRIVATE_KEY_NAMEF, PRIVATE_KEY_CODE},  
    {HELP_NAMEF, HELP_CODE},  
    {HELP_NAMES, HELP_CODE}  
};
